language: node_js
env:
  - NODESCREENSHOT_SHOW=1
node_js:
  - '0.12'
sudo: false
addons:
  apt:
    packages:
    - libcairo2
    - libfreetype6
    - libfontconfig1
    - libxcomposite1
    - libasound2
    - libxdamage1
    - libxext6
    - libxfixes3
    - libnss3
    - libnspr4
    - libexpat1
    - libudev0
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start +extension RANDR;