language: node_js
env:
  - NODESCREENSHOT_SHOW=1
node_js:
  - '0.12'
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start +extension RANDR;
  - sudo apt-get -qq update
  - sudo apt-get -y install libx11-6:i386;
  - sudo apt-get -y install libglib2.0-0:i386;
  - sudo apt-get -y install libgtk2.0-0:i386;
  - sudo apt-get -y install libatk1.0-0:i386;
  - sudo apt-get -y install libgdk-pixbuf2.0-0:i386;
  - sudo apt-get -y install libcairo2:i386;
  - sudo apt-get -y install libfreetype6:i386;
  - sudo apt-get -y install libfontconfig1:i386;
  - sudo apt-get -y install libxcomposite1:i386;
  - sudo apt-get -y install libasound2:i386;
  - sudo apt-get -y install libxdamage1:i386;
  - sudo apt-get -y install libxext6:i386;
  - sudo apt-get -y install libxfixes3:i386;
  - sudo apt-get -y install libnss3:i386;
  - sudo apt-get -y install libnspr4:i386;
  - sudo apt-get -y install libgconf-2-4:i386;
  - sudo apt-get -y install libexpat1:i386;
  - sudo apt-get -y install libdbus-1-3:i386;
  - sudo apt-get -y install libudev0:i386;